### PR TITLE
Date and City related fixes

### PR DESCRIPTION
**Pull request by saibaggins**
Fixed an issue with DialogFlow assuming year 2020 when the year is not explicitly mentioned and also fixed mapping between old city names and new city names like Bangalore and Bengaluru

### CODE REVIEW

**Comment by icyphox** [comment]
Just found time to look at this. LGTM.  
Although the hard coded `switch` case seems a _little_ hacky :)

**Comment by saibaggins** [comment]
Agreed waiting for the star devs to free up to clean up the cities & dates :)

**Comment by karthikmuralidharan** [comment]
@saibaggins should we take the approach discussed today regarding combined entities for cities and centres? I would assume that this approach would not be needed then.

**Comment by saibaggins** [comment]
> @saibaggins should we take the approach discussed today regarding combined entities for cities and centres? I would assume that this approach would not be needed then.

@karthikmuralidharan If you're referring to the changes that @Sundararam is working on, yes, we should do that. The changes I committed were interim to support the ongoing testing.

BTW the entities approach will not work, because training the entities for each of the spellings is a nightmare. We can discuss more.

**Pull request closed without merging**
